// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: offersrpc/offers.proto

package offersrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOfferRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The offer's description, shown to the payer. Required when an amount
	// is set. A mining pool that pays over BOLT 12 mandates its own text
	// here, for example "OCEAN Payouts for <bitcoin address>".
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// The amount the offer asks for, in millisatoshi. Zero lets the payer
	// choose the amount, which is what a pool payout needs.
	AmountMsat uint64 `protobuf:"varint,2,opt,name=amount_msat,json=amountMsat,proto3" json:"amount_msat,omitempty"`
	// When the offer stops being valid, as a Unix timestamp in seconds. Zero
	// means it does not expire.
	AbsoluteExpiry uint64 `protobuf:"varint,3,opt,name=absolute_expiry,json=absoluteExpiry,proto3" json:"absolute_expiry,omitempty"`
	// Free text naming who is being paid.
	Issuer string `protobuf:"bytes,4,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// The largest quantity a request may ask for. Zero leaves quantities
	// out of the offer unless quantity_any is set.
	QuantityMax uint64 `protobuf:"varint,5,opt,name=quantity_max,json=quantityMax,proto3" json:"quantity_max,omitempty"`
	// A note kept with the offer on this node only.
	Label string `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	// Put blinded paths on the offer even though the node announces an
	// address. Blinded paths hide the node id and let an unannounced node
	// be reached; they also make the offer string longer.
	WithPaths bool `protobuf:"varint,7,opt,name=with_paths,json=withPaths,proto3" json:"with_paths,omitempty"`
	// Never put blinded paths on the offer, even when the node announces no
	// address. Payers must then reach the node by its id.
	NoPaths bool `protobuf:"varint,8,opt,name=no_paths,json=noPaths,proto3" json:"no_paths,omitempty"`
	// Let a request ask for any quantity. Excludes quantity_max.
	QuantityAny   bool `protobuf:"varint,9,opt,name=quantity_any,json=quantityAny,proto3" json:"quantity_any,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOfferRequest) Reset() {
	*x = CreateOfferRequest{}
	mi := &file_offersrpc_offers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOfferRequest) ProtoMessage() {}

func (x *CreateOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offersrpc_offers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOfferRequest.ProtoReflect.Descriptor instead.
func (*CreateOfferRequest) Descriptor() ([]byte, []int) {
	return file_offersrpc_offers_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOfferRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateOfferRequest) GetAmountMsat() uint64 {
	if x != nil {
		return x.AmountMsat
	}
	return 0
}

func (x *CreateOfferRequest) GetAbsoluteExpiry() uint64 {
	if x != nil {
		return x.AbsoluteExpiry
	}
	return 0
}

func (x *CreateOfferRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *CreateOfferRequest) GetQuantityMax() uint64 {
	if x != nil {
		return x.QuantityMax
	}
	return 0
}

func (x *CreateOfferRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateOfferRequest) GetWithPaths() bool {
	if x != nil {
		return x.WithPaths
	}
	return false
}

func (x *CreateOfferRequest) GetNoPaths() bool {
	if x != nil {
		return x.NoPaths
	}
	return false
}

func (x *CreateOfferRequest) GetQuantityAny() bool {
	if x != nil {
		return x.QuantityAny
	}
	return false
}

type Offer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The offer id: the BOLT 12 Merkle root of the offer's fields.
	OfferId []byte `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	// The offer as a bech32 string, lno1..., to hand to payers.
	Bolt12 string `protobuf:"bytes,2,opt,name=bolt12,proto3" json:"bolt12,omitempty"`
	// The offer's description, if any.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// The amount the offer asks for in millisatoshi, or zero for any.
	AmountMsat uint64 `protobuf:"varint,4,opt,name=amount_msat,json=amountMsat,proto3" json:"amount_msat,omitempty"`
	// When the offer expires as a Unix timestamp, or zero for never.
	AbsoluteExpiry uint64 `protobuf:"varint,5,opt,name=absolute_expiry,json=absoluteExpiry,proto3" json:"absolute_expiry,omitempty"`
	// When this node minted the offer, as a Unix timestamp. Zero for an
	// offer this node did not mint.
	CreatedAt uint64 `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Whether this node serves the offer. False for a disabled offer, and
	// for an offer this node did not mint.
	Active bool `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	// How many invoices this node has issued for the offer.
	InvoicesIssued uint64 `protobuf:"varint,8,opt,name=invoices_issued,json=invoicesIssued,proto3" json:"invoices_issued,omitempty"`
	// The operator's note, kept on this node only.
	Label string `protobuf:"bytes,9,opt,name=label,proto3" json:"label,omitempty"`
	// The node id that signs the offer's invoices, offer_issuer_id, if the
	// offer names one.
	IssuerId []byte `protobuf:"bytes,10,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	// How many blinded paths the offer carries.
	NumPaths uint32 `protobuf:"varint,11,opt,name=num_paths,json=numPaths,proto3" json:"num_paths,omitempty"`
	// The chains the offer names. An offer that names none is for Bitcoin
	// mainnet, which is not this node's chain.
	Chains [][]byte `protobuf:"bytes,12,rep,name=chains,proto3" json:"chains,omitempty"`
	// Free text naming who is being paid, offer_issuer, if any.
	Issuer string `protobuf:"bytes,13,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// The largest quantity a request may ask for, if the offer sets one.
	// Zero with quantity_any set means any quantity.
	QuantityMax uint64 `protobuf:"varint,14,opt,name=quantity_max,json=quantityMax,proto3" json:"quantity_max,omitempty"`
	// Whether a request may ask for any quantity.
	QuantityAny   bool `protobuf:"varint,15,opt,name=quantity_any,json=quantityAny,proto3" json:"quantity_any,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offer) Reset() {
	*x = Offer{}
	mi := &file_offersrpc_offers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_offersrpc_offers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_offersrpc_offers_proto_rawDescGZIP(), []int{1}
}

func (x *Offer) GetOfferId() []byte {
	if x != nil {
		return x.OfferId
	}
	return nil
}

func (x *Offer) GetBolt12() string {
	if x != nil {
		return x.Bolt12
	}
	return ""
}

func (x *Offer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Offer) GetAmountMsat() uint64 {
	if x != nil {
		return x.AmountMsat
	}
	return 0
}

func (x *Offer) GetAbsoluteExpiry() uint64 {
	if x != nil {
		return x.AbsoluteExpiry
	}
	return 0
}

func (x *Offer) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Offer) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Offer) GetInvoicesIssued() uint64 {
	if x != nil {
		return x.InvoicesIssued
	}
	return 0
}

func (x *Offer) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Offer) GetIssuerId() []byte {
	if x != nil {
		return x.IssuerId
	}
	return nil
}

func (x *Offer) GetNumPaths() uint32 {
	if x != nil {
		return x.NumPaths
	}
	return 0
}

func (x *Offer) GetChains() [][]byte {
	if x != nil {
		return x.Chains
	}
	return nil
}

func (x *Offer) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Offer) GetQuantityMax() uint64 {
	if x != nil {
		return x.QuantityMax
	}
	return 0
}

func (x *Offer) GetQuantityAny() bool {
	if x != nil {
		return x.QuantityAny
	}
	return false
}

type CreateOfferResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Offer *Offer                 `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
	// Whether the offer was minted now. The same fields always mint the same
	// offer, so minting it again returns the stored offer with this false.
	Created       bool `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOfferResponse) Reset() {
	*x = CreateOfferResponse{}
	mi := &file_offersrpc_offers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOfferResponse) ProtoMessage() {}

func (x *CreateOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offersrpc_offers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOfferResponse.ProtoReflect.Descriptor instead.
func (*CreateOfferResponse) Descriptor() ([]byte, []int) {
	return file_offersrpc_offers_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOfferResponse) GetOffer() *Offer {
	if x != nil {
		return x.Offer
	}
	return nil
}

func (x *CreateOfferResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type ListOffersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List only offers that are enabled.
	ActiveOnly    bool `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOffersRequest) Reset() {
	*x = ListOffersRequest{}
	mi := &file_offersrpc_offers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOffersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOffersRequest) ProtoMessage() {}

func (x *ListOffersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offersrpc_offers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOffersRequest.ProtoReflect.Descriptor instead.
func (*ListOffersRequest) Descriptor() ([]byte, []int) {
	return file_offersrpc_offers_proto_rawDescGZIP(), []int{3}
}

func (x *ListOffersRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type ListOffersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        []*Offer               `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOffersResponse) Reset() {
	*x = ListOffersResponse{}
	mi := &file_offersrpc_offers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOffersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOffersResponse) ProtoMessage() {}

func (x *ListOffersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offersrpc_offers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOffersResponse.ProtoReflect.Descriptor instead.
func (*ListOffersResponse) Descriptor() ([]byte, []int) {
	return file_offersrpc_offers_proto_rawDescGZIP(), []int{4}
}

func (x *ListOffersResponse) GetOffers() []*Offer {
	if x != nil {
		return x.Offers
	}
	return nil
}

type DisableOfferRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the offer to disable.
	OfferId       []byte `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableOfferRequest) Reset() {
	*x = DisableOfferRequest{}
	mi := &file_offersrpc_offers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableOfferRequest) ProtoMessage() {}

func (x *DisableOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offersrpc_offers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableOfferRequest.ProtoReflect.Descriptor instead.
func (*DisableOfferRequest) Descriptor() ([]byte, []int) {
	return file_offersrpc_offers_proto_rawDescGZIP(), []int{5}
}

func (x *DisableOfferRequest) GetOfferId() []byte {
	if x != nil {
		return x.OfferId
	}
	return nil
}

type DisableOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableOfferResponse) Reset() {
	*x = DisableOfferResponse{}
	mi := &file_offersrpc_offers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableOfferResponse) ProtoMessage() {}

func (x *DisableOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offersrpc_offers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableOfferResponse.ProtoReflect.Descriptor instead.
func (*DisableOfferResponse) Descriptor() ([]byte, []int) {
	return file_offersrpc_offers_proto_rawDescGZIP(), []int{6}
}

type EnableOfferRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the offer to enable.
	OfferId       []byte `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableOfferRequest) Reset() {
	*x = EnableOfferRequest{}
	mi := &file_offersrpc_offers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableOfferRequest) ProtoMessage() {}

func (x *EnableOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offersrpc_offers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableOfferRequest.ProtoReflect.Descriptor instead.
func (*EnableOfferRequest) Descriptor() ([]byte, []int) {
	return file_offersrpc_offers_proto_rawDescGZIP(), []int{7}
}

func (x *EnableOfferRequest) GetOfferId() []byte {
	if x != nil {
		return x.OfferId
	}
	return nil
}

type EnableOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableOfferResponse) Reset() {
	*x = EnableOfferResponse{}
	mi := &file_offersrpc_offers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableOfferResponse) ProtoMessage() {}

func (x *EnableOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offersrpc_offers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableOfferResponse.ProtoReflect.Descriptor instead.
func (*EnableOfferResponse) Descriptor() ([]byte, []int) {
	return file_offersrpc_offers_proto_rawDescGZIP(), []int{8}
}

type DecodeBolt12Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An offer, invoice request or invoice string.
	Bolt12        string `protobuf:"bytes,1,opt,name=bolt12,proto3" json:"bolt12,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeBolt12Request) Reset() {
	*x = DecodeBolt12Request{}
	mi := &file_offersrpc_offers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeBolt12Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeBolt12Request) ProtoMessage() {}

func (x *DecodeBolt12Request) ProtoReflect() protoreflect.Message {
	mi := &file_offersrpc_offers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeBolt12Request.ProtoReflect.Descriptor instead.
func (*DecodeBolt12Request) Descriptor() ([]byte, []int) {
	return file_offersrpc_offers_proto_rawDescGZIP(), []int{9}
}

func (x *DecodeBolt12Request) GetBolt12() string {
	if x != nil {
		return x.Bolt12
	}
	return ""
}

type InvoiceRequestInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payer's key for this request, invreq_payer_id.
	PayerId []byte `protobuf:"bytes,1,opt,name=payer_id,json=payerId,proto3" json:"payer_id,omitempty"`
	// The amount requested in millisatoshi, if the request sets one.
	AmountMsat uint64 `protobuf:"varint,2,opt,name=amount_msat,json=amountMsat,proto3" json:"amount_msat,omitempty"`
	// The quantity requested, if the request sets one.
	Quantity uint64 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// The payer's note, if any.
	PayerNote string `protobuf:"bytes,4,opt,name=payer_note,json=payerNote,proto3" json:"payer_note,omitempty"`
	// The payer's metadata, invreq_metadata.
	Metadata []byte `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Whether the request carries a valid signature by payer_id. Always
	// false for the request fields mirrored in an invoice, which carries the
	// issuer's signature instead.
	SignatureValid bool `protobuf:"varint,6,opt,name=signature_valid,json=signatureValid,proto3" json:"signature_valid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvoiceRequestInfo) Reset() {
	*x = InvoiceRequestInfo{}
	mi := &file_offersrpc_offers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceRequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceRequestInfo) ProtoMessage() {}

func (x *InvoiceRequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_offersrpc_offers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceRequestInfo.ProtoReflect.Descriptor instead.
func (*InvoiceRequestInfo) Descriptor() ([]byte, []int) {
	return file_offersrpc_offers_proto_rawDescGZIP(), []int{10}
}

func (x *InvoiceRequestInfo) GetPayerId() []byte {
	if x != nil {
		return x.PayerId
	}
	return nil
}

func (x *InvoiceRequestInfo) GetAmountMsat() uint64 {
	if x != nil {
		return x.AmountMsat
	}
	return 0
}

func (x *InvoiceRequestInfo) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *InvoiceRequestInfo) GetPayerNote() string {
	if x != nil {
		return x.PayerNote
	}
	return ""
}

func (x *InvoiceRequestInfo) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InvoiceRequestInfo) GetSignatureValid() bool {
	if x != nil {
		return x.SignatureValid
	}
	return false
}

type InvoiceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payment hash to pay to.
	PaymentHash []byte `protobuf:"bytes,1,opt,name=payment_hash,json=paymentHash,proto3" json:"payment_hash,omitempty"`
	// The amount in millisatoshi.
	AmountMsat uint64 `protobuf:"varint,2,opt,name=amount_msat,json=amountMsat,proto3" json:"amount_msat,omitempty"`
	// The node id that signed the invoice, invoice_node_id.
	NodeId []byte `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// When the invoice was created, as a Unix timestamp.
	CreatedAt uint64 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// How long the invoice is valid after created_at, in seconds.
	RelativeExpiry uint32 `protobuf:"varint,5,opt,name=relative_expiry,json=relativeExpiry,proto3" json:"relative_expiry,omitempty"`
	// How many blinded payment paths the invoice carries.
	NumPaths uint32 `protobuf:"varint,6,opt,name=num_paths,json=numPaths,proto3" json:"num_paths,omitempty"`
	// The payer's key the invoice answers, invreq_payer_id.
	PayerId []byte `protobuf:"bytes,7,opt,name=payer_id,json=payerId,proto3" json:"payer_id,omitempty"`
	// Whether the invoice carries a valid signature by node_id.
	SignatureValid bool `protobuf:"varint,8,opt,name=signature_valid,json=signatureValid,proto3" json:"signature_valid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvoiceInfo) Reset() {
	*x = InvoiceInfo{}
	mi := &file_offersrpc_offers_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceInfo) ProtoMessage() {}

func (x *InvoiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_offersrpc_offers_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceInfo.ProtoReflect.Descriptor instead.
func (*InvoiceInfo) Descriptor() ([]byte, []int) {
	return file_offersrpc_offers_proto_rawDescGZIP(), []int{11}
}

func (x *InvoiceInfo) GetPaymentHash() []byte {
	if x != nil {
		return x.PaymentHash
	}
	return nil
}

func (x *InvoiceInfo) GetAmountMsat() uint64 {
	if x != nil {
		return x.AmountMsat
	}
	return 0
}

func (x *InvoiceInfo) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *InvoiceInfo) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *InvoiceInfo) GetRelativeExpiry() uint32 {
	if x != nil {
		return x.RelativeExpiry
	}
	return 0
}

func (x *InvoiceInfo) GetNumPaths() uint32 {
	if x != nil {
		return x.NumPaths
	}
	return 0
}

func (x *InvoiceInfo) GetPayerId() []byte {
	if x != nil {
		return x.PayerId
	}
	return nil
}

func (x *InvoiceInfo) GetSignatureValid() bool {
	if x != nil {
		return x.SignatureValid
	}
	return false
}

type DecodeBolt12Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What the string is: "offer", "invoice_request" or "invoice".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Whether the message names this node's chain, read from its chain
	// fields alone. A message for another chain still decodes, so its chain
	// can be shown.
	ForThisChain bool `protobuf:"varint,2,opt,name=for_this_chain,json=forThisChain,proto3" json:"for_this_chain,omitempty"`
	// The chains the message names. Empty means it names none, which BOLT 12
	// reads as Bitcoin mainnet.
	Chains [][]byte `protobuf:"bytes,3,rep,name=chains,proto3" json:"chains,omitempty"`
	// The id of the offer the message is or mirrors, if it has one.
	OfferId []byte `protobuf:"bytes,4,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	// The offer's fields, for an offer, or the mirrored offer fields for a
	// request or invoice.
	Offer *Offer `protobuf:"bytes,5,opt,name=offer,proto3" json:"offer,omitempty"`
	// The request's own fields, for an invoice request or an invoice.
	InvoiceRequest *InvoiceRequestInfo `protobuf:"bytes,6,opt,name=invoice_request,json=invoiceRequest,proto3" json:"invoice_request,omitempty"`
	// The invoice's own fields, for an invoice.
	Invoice *InvoiceInfo `protobuf:"bytes,7,opt,name=invoice,proto3" json:"invoice,omitempty"`
	// For an offer: whether it passes the reader checks for this chain and
	// the current time. A request or invoice is not validated here, since
	// that needs the offer it answers.
	Valid bool `protobuf:"varint,8,opt,name=valid,proto3" json:"valid,omitempty"`
	// Why the offer is not valid, when it is not.
	ValidationError string `protobuf:"bytes,9,opt,name=validation_error,json=validationError,proto3" json:"validation_error,omitempty"`
	// Whether this node minted the offer.
	Ours          bool `protobuf:"varint,10,opt,name=ours,proto3" json:"ours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeBolt12Response) Reset() {
	*x = DecodeBolt12Response{}
	mi := &file_offersrpc_offers_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeBolt12Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeBolt12Response) ProtoMessage() {}

func (x *DecodeBolt12Response) ProtoReflect() protoreflect.Message {
	mi := &file_offersrpc_offers_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeBolt12Response.ProtoReflect.Descriptor instead.
func (*DecodeBolt12Response) Descriptor() ([]byte, []int) {
	return file_offersrpc_offers_proto_rawDescGZIP(), []int{12}
}

func (x *DecodeBolt12Response) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DecodeBolt12Response) GetForThisChain() bool {
	if x != nil {
		return x.ForThisChain
	}
	return false
}

func (x *DecodeBolt12Response) GetChains() [][]byte {
	if x != nil {
		return x.Chains
	}
	return nil
}

func (x *DecodeBolt12Response) GetOfferId() []byte {
	if x != nil {
		return x.OfferId
	}
	return nil
}

func (x *DecodeBolt12Response) GetOffer() *Offer {
	if x != nil {
		return x.Offer
	}
	return nil
}

func (x *DecodeBolt12Response) GetInvoiceRequest() *InvoiceRequestInfo {
	if x != nil {
		return x.InvoiceRequest
	}
	return nil
}

func (x *DecodeBolt12Response) GetInvoice() *InvoiceInfo {
	if x != nil {
		return x.Invoice
	}
	return nil
}

func (x *DecodeBolt12Response) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *DecodeBolt12Response) GetValidationError() string {
	if x != nil {
		return x.ValidationError
	}
	return ""
}

func (x *DecodeBolt12Response) GetOurs() bool {
	if x != nil {
		return x.Ours
	}
	return false
}

var File_offersrpc_offers_proto protoreflect.FileDescriptor

const file_offersrpc_offers_proto_rawDesc = "" +
	"\n" +
	"\x16offersrpc/offers.proto\x12\toffersrpc\"\xae\x02\n" +
	"\x12CreateOfferRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1f\n" +
	"\vamount_msat\x18\x02 \x01(\x04R\n" +
	"amountMsat\x12'\n" +
	"\x0fabsolute_expiry\x18\x03 \x01(\x04R\x0eabsoluteExpiry\x12\x16\n" +
	"\x06issuer\x18\x04 \x01(\tR\x06issuer\x12!\n" +
	"\fquantity_max\x18\x05 \x01(\x04R\vquantityMax\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\x12\x1d\n" +
	"\n" +
	"with_paths\x18\a \x01(\bR\twithPaths\x12\x19\n" +
	"\bno_paths\x18\b \x01(\bR\anoPaths\x12!\n" +
	"\fquantity_any\x18\t \x01(\bR\vquantityAny\"\xcc\x03\n" +
	"\x05Offer\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\fR\aofferId\x12\x16\n" +
	"\x06bolt12\x18\x02 \x01(\tR\x06bolt12\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vamount_msat\x18\x04 \x01(\x04R\n" +
	"amountMsat\x12'\n" +
	"\x0fabsolute_expiry\x18\x05 \x01(\x04R\x0eabsoluteExpiry\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x04R\tcreatedAt\x12\x16\n" +
	"\x06active\x18\a \x01(\bR\x06active\x12'\n" +
	"\x0finvoices_issued\x18\b \x01(\x04R\x0einvoicesIssued\x12\x14\n" +
	"\x05label\x18\t \x01(\tR\x05label\x12\x1b\n" +
	"\tissuer_id\x18\n" +
	" \x01(\fR\bissuerId\x12\x1b\n" +
	"\tnum_paths\x18\v \x01(\rR\bnumPaths\x12\x16\n" +
	"\x06chains\x18\f \x03(\fR\x06chains\x12\x16\n" +
	"\x06issuer\x18\r \x01(\tR\x06issuer\x12!\n" +
	"\fquantity_max\x18\x0e \x01(\x04R\vquantityMax\x12!\n" +
	"\fquantity_any\x18\x0f \x01(\bR\vquantityAny\"W\n" +
	"\x13CreateOfferResponse\x12&\n" +
	"\x05offer\x18\x01 \x01(\v2\x10.offersrpc.OfferR\x05offer\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"4\n" +
	"\x11ListOffersRequest\x12\x1f\n" +
	"\vactive_only\x18\x01 \x01(\bR\n" +
	"activeOnly\">\n" +
	"\x12ListOffersResponse\x12(\n" +
	"\x06offers\x18\x01 \x03(\v2\x10.offersrpc.OfferR\x06offers\"0\n" +
	"\x13DisableOfferRequest\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\fR\aofferId\"\x16\n" +
	"\x14DisableOfferResponse\"/\n" +
	"\x12EnableOfferRequest\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\fR\aofferId\"\x15\n" +
	"\x13EnableOfferResponse\"-\n" +
	"\x13DecodeBolt12Request\x12\x16\n" +
	"\x06bolt12\x18\x01 \x01(\tR\x06bolt12\"\xd0\x01\n" +
	"\x12InvoiceRequestInfo\x12\x19\n" +
	"\bpayer_id\x18\x01 \x01(\fR\apayerId\x12\x1f\n" +
	"\vamount_msat\x18\x02 \x01(\x04R\n" +
	"amountMsat\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x04R\bquantity\x12\x1d\n" +
	"\n" +
	"payer_note\x18\x04 \x01(\tR\tpayerNote\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\fR\bmetadata\x12'\n" +
	"\x0fsignature_valid\x18\x06 \x01(\bR\x0esignatureValid\"\x93\x02\n" +
	"\vInvoiceInfo\x12!\n" +
	"\fpayment_hash\x18\x01 \x01(\fR\vpaymentHash\x12\x1f\n" +
	"\vamount_msat\x18\x02 \x01(\x04R\n" +
	"amountMsat\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\fR\x06nodeId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x04R\tcreatedAt\x12'\n" +
	"\x0frelative_expiry\x18\x05 \x01(\rR\x0erelativeExpiry\x12\x1b\n" +
	"\tnum_paths\x18\x06 \x01(\rR\bnumPaths\x12\x19\n" +
	"\bpayer_id\x18\a \x01(\fR\apayerId\x12'\n" +
	"\x0fsignature_valid\x18\b \x01(\bR\x0esignatureValid\"\xfa\x02\n" +
	"\x14DecodeBolt12Response\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12$\n" +
	"\x0efor_this_chain\x18\x02 \x01(\bR\fforThisChain\x12\x16\n" +
	"\x06chains\x18\x03 \x03(\fR\x06chains\x12\x19\n" +
	"\boffer_id\x18\x04 \x01(\fR\aofferId\x12&\n" +
	"\x05offer\x18\x05 \x01(\v2\x10.offersrpc.OfferR\x05offer\x12F\n" +
	"\x0finvoice_request\x18\x06 \x01(\v2\x1d.offersrpc.InvoiceRequestInfoR\x0einvoiceRequest\x120\n" +
	"\ainvoice\x18\a \x01(\v2\x16.offersrpc.InvoiceInfoR\ainvoice\x12\x14\n" +
	"\x05valid\x18\b \x01(\bR\x05valid\x12)\n" +
	"\x10validation_error\x18\t \x01(\tR\x0fvalidationError\x12\x12\n" +
	"\x04ours\x18\n" +
	" \x01(\bR\x04ours2\x91\x03\n" +
	"\x06Offers\x12L\n" +
	"\vCreateOffer\x12\x1d.offersrpc.CreateOfferRequest\x1a\x1e.offersrpc.CreateOfferResponse\x12I\n" +
	"\n" +
	"ListOffers\x12\x1c.offersrpc.ListOffersRequest\x1a\x1d.offersrpc.ListOffersResponse\x12O\n" +
	"\fDisableOffer\x12\x1e.offersrpc.DisableOfferRequest\x1a\x1f.offersrpc.DisableOfferResponse\x12L\n" +
	"\vEnableOffer\x12\x1d.offersrpc.EnableOfferRequest\x1a\x1e.offersrpc.EnableOfferResponse\x12O\n" +
	"\fDecodeBolt12\x12\x1e.offersrpc.DecodeBolt12Request\x1a\x1f.offersrpc.DecodeBolt12ResponseB1Z/github.com/lightningnetwork/lnd/lnrpc/offersrpcb\x06proto3"

var (
	file_offersrpc_offers_proto_rawDescOnce sync.Once
	file_offersrpc_offers_proto_rawDescData []byte
)

func file_offersrpc_offers_proto_rawDescGZIP() []byte {
	file_offersrpc_offers_proto_rawDescOnce.Do(func() {
		file_offersrpc_offers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_offersrpc_offers_proto_rawDesc), len(file_offersrpc_offers_proto_rawDesc)))
	})
	return file_offersrpc_offers_proto_rawDescData
}

var file_offersrpc_offers_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_offersrpc_offers_proto_goTypes = []any{
	(*CreateOfferRequest)(nil),   // 0: offersrpc.CreateOfferRequest
	(*Offer)(nil),                // 1: offersrpc.Offer
	(*CreateOfferResponse)(nil),  // 2: offersrpc.CreateOfferResponse
	(*ListOffersRequest)(nil),    // 3: offersrpc.ListOffersRequest
	(*ListOffersResponse)(nil),   // 4: offersrpc.ListOffersResponse
	(*DisableOfferRequest)(nil),  // 5: offersrpc.DisableOfferRequest
	(*DisableOfferResponse)(nil), // 6: offersrpc.DisableOfferResponse
	(*EnableOfferRequest)(nil),   // 7: offersrpc.EnableOfferRequest
	(*EnableOfferResponse)(nil),  // 8: offersrpc.EnableOfferResponse
	(*DecodeBolt12Request)(nil),  // 9: offersrpc.DecodeBolt12Request
	(*InvoiceRequestInfo)(nil),   // 10: offersrpc.InvoiceRequestInfo
	(*InvoiceInfo)(nil),          // 11: offersrpc.InvoiceInfo
	(*DecodeBolt12Response)(nil), // 12: offersrpc.DecodeBolt12Response
}
var file_offersrpc_offers_proto_depIdxs = []int32{
	1,  // 0: offersrpc.CreateOfferResponse.offer:type_name -> offersrpc.Offer
	1,  // 1: offersrpc.ListOffersResponse.offers:type_name -> offersrpc.Offer
	1,  // 2: offersrpc.DecodeBolt12Response.offer:type_name -> offersrpc.Offer
	10, // 3: offersrpc.DecodeBolt12Response.invoice_request:type_name -> offersrpc.InvoiceRequestInfo
	11, // 4: offersrpc.DecodeBolt12Response.invoice:type_name -> offersrpc.InvoiceInfo
	0,  // 5: offersrpc.Offers.CreateOffer:input_type -> offersrpc.CreateOfferRequest
	3,  // 6: offersrpc.Offers.ListOffers:input_type -> offersrpc.ListOffersRequest
	5,  // 7: offersrpc.Offers.DisableOffer:input_type -> offersrpc.DisableOfferRequest
	7,  // 8: offersrpc.Offers.EnableOffer:input_type -> offersrpc.EnableOfferRequest
	9,  // 9: offersrpc.Offers.DecodeBolt12:input_type -> offersrpc.DecodeBolt12Request
	2,  // 10: offersrpc.Offers.CreateOffer:output_type -> offersrpc.CreateOfferResponse
	4,  // 11: offersrpc.Offers.ListOffers:output_type -> offersrpc.ListOffersResponse
	6,  // 12: offersrpc.Offers.DisableOffer:output_type -> offersrpc.DisableOfferResponse
	8,  // 13: offersrpc.Offers.EnableOffer:output_type -> offersrpc.EnableOfferResponse
	12, // 14: offersrpc.Offers.DecodeBolt12:output_type -> offersrpc.DecodeBolt12Response
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_offersrpc_offers_proto_init() }
func file_offersrpc_offers_proto_init() {
	if File_offersrpc_offers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_offersrpc_offers_proto_rawDesc), len(file_offersrpc_offers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_offersrpc_offers_proto_goTypes,
		DependencyIndexes: file_offersrpc_offers_proto_depIdxs,
		MessageInfos:      file_offersrpc_offers_proto_msgTypes,
	}.Build()
	File_offersrpc_offers_proto = out.File
	file_offersrpc_offers_proto_goTypes = nil
	file_offersrpc_offers_proto_depIdxs = nil
}
