// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package offersrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OffersClient is the client API for Offers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OffersClient interface {
	// lncli: `offer create`
	// CreateOffer mints a BOLT 12 offer for this node's chain and stores it. The
	// node answers invoice requests for it over onion messages for as long as
	// it is active and unexpired.
	CreateOffer(ctx context.Context, in *CreateOfferRequest, opts ...grpc.CallOption) (*CreateOfferResponse, error)
	// lncli: `offer list`
	// ListOffers lists the offers this node has minted, newest first.
	ListOffers(ctx context.Context, in *ListOffersRequest, opts ...grpc.CallOption) (*ListOffersResponse, error)
	// lncli: `offer disable`
	// DisableOffer stops the node from serving an offer. The offer stays listed
	// and can be enabled again.
	DisableOffer(ctx context.Context, in *DisableOfferRequest, opts ...grpc.CallOption) (*DisableOfferResponse, error)
	// lncli: `offer enable`
	// EnableOffer resumes serving a disabled offer.
	EnableOffer(ctx context.Context, in *EnableOfferRequest, opts ...grpc.CallOption) (*EnableOfferResponse, error)
	// lncli: `offer decode`
	// DecodeBolt12 decodes an offer (lno1...), invoice request (lnr1...) or
	// invoice (lni1...) and reports which chain it names.
	DecodeBolt12(ctx context.Context, in *DecodeBolt12Request, opts ...grpc.CallOption) (*DecodeBolt12Response, error)
	// lncli: `offer fetchinvoice`
	// FetchInvoice asks an offer's issuer for an invoice over onion messages
	// and returns it once it has been checked against the request. Nothing is
	// paid.
	FetchInvoice(ctx context.Context, in *FetchInvoiceRequest, opts ...grpc.CallOption) (*FetchInvoiceResponse, error)
	// lncli: `offer pay`
	// PayOffer fetches an invoice for an offer and pays it, or pays an invoice
	// fetched earlier. It returns when the payment succeeds or fails.
	PayOffer(ctx context.Context, in *PayOfferRequest, opts ...grpc.CallOption) (*PayOfferResponse, error)
	// lncli: `offer invoices`
	// ListOfferInvoices lists the invoices this node has issued for its
	// offers, with their state in the invoice registry.
	ListOfferInvoices(ctx context.Context, in *ListOfferInvoicesRequest, opts ...grpc.CallOption) (*ListOfferInvoicesResponse, error)
}

type offersClient struct {
	cc grpc.ClientConnInterface
}

func NewOffersClient(cc grpc.ClientConnInterface) OffersClient {
	return &offersClient{cc}
}

func (c *offersClient) CreateOffer(ctx context.Context, in *CreateOfferRequest, opts ...grpc.CallOption) (*CreateOfferResponse, error) {
	out := new(CreateOfferResponse)
	err := c.cc.Invoke(ctx, "/offersrpc.Offers/CreateOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offersClient) ListOffers(ctx context.Context, in *ListOffersRequest, opts ...grpc.CallOption) (*ListOffersResponse, error) {
	out := new(ListOffersResponse)
	err := c.cc.Invoke(ctx, "/offersrpc.Offers/ListOffers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offersClient) DisableOffer(ctx context.Context, in *DisableOfferRequest, opts ...grpc.CallOption) (*DisableOfferResponse, error) {
	out := new(DisableOfferResponse)
	err := c.cc.Invoke(ctx, "/offersrpc.Offers/DisableOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offersClient) EnableOffer(ctx context.Context, in *EnableOfferRequest, opts ...grpc.CallOption) (*EnableOfferResponse, error) {
	out := new(EnableOfferResponse)
	err := c.cc.Invoke(ctx, "/offersrpc.Offers/EnableOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offersClient) DecodeBolt12(ctx context.Context, in *DecodeBolt12Request, opts ...grpc.CallOption) (*DecodeBolt12Response, error) {
	out := new(DecodeBolt12Response)
	err := c.cc.Invoke(ctx, "/offersrpc.Offers/DecodeBolt12", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offersClient) FetchInvoice(ctx context.Context, in *FetchInvoiceRequest, opts ...grpc.CallOption) (*FetchInvoiceResponse, error) {
	out := new(FetchInvoiceResponse)
	err := c.cc.Invoke(ctx, "/offersrpc.Offers/FetchInvoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offersClient) PayOffer(ctx context.Context, in *PayOfferRequest, opts ...grpc.CallOption) (*PayOfferResponse, error) {
	out := new(PayOfferResponse)
	err := c.cc.Invoke(ctx, "/offersrpc.Offers/PayOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offersClient) ListOfferInvoices(ctx context.Context, in *ListOfferInvoicesRequest, opts ...grpc.CallOption) (*ListOfferInvoicesResponse, error) {
	out := new(ListOfferInvoicesResponse)
	err := c.cc.Invoke(ctx, "/offersrpc.Offers/ListOfferInvoices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OffersServer is the server API for Offers service.
// All implementations must embed UnimplementedOffersServer
// for forward compatibility
type OffersServer interface {
	// lncli: `offer create`
	// CreateOffer mints a BOLT 12 offer for this node's chain and stores it. The
	// node answers invoice requests for it over onion messages for as long as
	// it is active and unexpired.
	CreateOffer(context.Context, *CreateOfferRequest) (*CreateOfferResponse, error)
	// lncli: `offer list`
	// ListOffers lists the offers this node has minted, newest first.
	ListOffers(context.Context, *ListOffersRequest) (*ListOffersResponse, error)
	// lncli: `offer disable`
	// DisableOffer stops the node from serving an offer. The offer stays listed
	// and can be enabled again.
	DisableOffer(context.Context, *DisableOfferRequest) (*DisableOfferResponse, error)
	// lncli: `offer enable`
	// EnableOffer resumes serving a disabled offer.
	EnableOffer(context.Context, *EnableOfferRequest) (*EnableOfferResponse, error)
	// lncli: `offer decode`
	// DecodeBolt12 decodes an offer (lno1...), invoice request (lnr1...) or
	// invoice (lni1...) and reports which chain it names.
	DecodeBolt12(context.Context, *DecodeBolt12Request) (*DecodeBolt12Response, error)
	// lncli: `offer fetchinvoice`
	// FetchInvoice asks an offer's issuer for an invoice over onion messages
	// and returns it once it has been checked against the request. Nothing is
	// paid.
	FetchInvoice(context.Context, *FetchInvoiceRequest) (*FetchInvoiceResponse, error)
	// lncli: `offer pay`
	// PayOffer fetches an invoice for an offer and pays it, or pays an invoice
	// fetched earlier. It returns when the payment succeeds or fails.
	PayOffer(context.Context, *PayOfferRequest) (*PayOfferResponse, error)
	// lncli: `offer invoices`
	// ListOfferInvoices lists the invoices this node has issued for its
	// offers, with their state in the invoice registry.
	ListOfferInvoices(context.Context, *ListOfferInvoicesRequest) (*ListOfferInvoicesResponse, error)
	mustEmbedUnimplementedOffersServer()
}

// UnimplementedOffersServer must be embedded to have forward compatible implementations.
type UnimplementedOffersServer struct {
}

func (UnimplementedOffersServer) CreateOffer(context.Context, *CreateOfferRequest) (*CreateOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOffer not implemented")
}
func (UnimplementedOffersServer) ListOffers(context.Context, *ListOffersRequest) (*ListOffersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOffers not implemented")
}
func (UnimplementedOffersServer) DisableOffer(context.Context, *DisableOfferRequest) (*DisableOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableOffer not implemented")
}
func (UnimplementedOffersServer) EnableOffer(context.Context, *EnableOfferRequest) (*EnableOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableOffer not implemented")
}
func (UnimplementedOffersServer) DecodeBolt12(context.Context, *DecodeBolt12Request) (*DecodeBolt12Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecodeBolt12 not implemented")
}
func (UnimplementedOffersServer) FetchInvoice(context.Context, *FetchInvoiceRequest) (*FetchInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchInvoice not implemented")
}
func (UnimplementedOffersServer) PayOffer(context.Context, *PayOfferRequest) (*PayOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayOffer not implemented")
}
func (UnimplementedOffersServer) ListOfferInvoices(context.Context, *ListOfferInvoicesRequest) (*ListOfferInvoicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOfferInvoices not implemented")
}
func (UnimplementedOffersServer) mustEmbedUnimplementedOffersServer() {}

// UnsafeOffersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OffersServer will
// result in compilation errors.
type UnsafeOffersServer interface {
	mustEmbedUnimplementedOffersServer()
}

func RegisterOffersServer(s grpc.ServiceRegistrar, srv OffersServer) {
	s.RegisterService(&Offers_ServiceDesc, srv)
}

func _Offers_CreateOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OffersServer).CreateOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/offersrpc.Offers/CreateOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OffersServer).CreateOffer(ctx, req.(*CreateOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Offers_ListOffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOffersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OffersServer).ListOffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/offersrpc.Offers/ListOffers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OffersServer).ListOffers(ctx, req.(*ListOffersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Offers_DisableOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OffersServer).DisableOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/offersrpc.Offers/DisableOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OffersServer).DisableOffer(ctx, req.(*DisableOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Offers_EnableOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OffersServer).EnableOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/offersrpc.Offers/EnableOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OffersServer).EnableOffer(ctx, req.(*EnableOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Offers_DecodeBolt12_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeBolt12Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OffersServer).DecodeBolt12(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/offersrpc.Offers/DecodeBolt12",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OffersServer).DecodeBolt12(ctx, req.(*DecodeBolt12Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Offers_FetchInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OffersServer).FetchInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/offersrpc.Offers/FetchInvoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OffersServer).FetchInvoice(ctx, req.(*FetchInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Offers_PayOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OffersServer).PayOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/offersrpc.Offers/PayOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OffersServer).PayOffer(ctx, req.(*PayOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Offers_ListOfferInvoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOfferInvoicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OffersServer).ListOfferInvoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/offersrpc.Offers/ListOfferInvoices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OffersServer).ListOfferInvoices(ctx, req.(*ListOfferInvoicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Offers_ServiceDesc is the grpc.ServiceDesc for Offers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Offers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "offersrpc.Offers",
	HandlerType: (*OffersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOffer",
			Handler:    _Offers_CreateOffer_Handler,
		},
		{
			MethodName: "ListOffers",
			Handler:    _Offers_ListOffers_Handler,
		},
		{
			MethodName: "DisableOffer",
			Handler:    _Offers_DisableOffer_Handler,
		},
		{
			MethodName: "EnableOffer",
			Handler:    _Offers_EnableOffer_Handler,
		},
		{
			MethodName: "DecodeBolt12",
			Handler:    _Offers_DecodeBolt12_Handler,
		},
		{
			MethodName: "FetchInvoice",
			Handler:    _Offers_FetchInvoice_Handler,
		},
		{
			MethodName: "PayOffer",
			Handler:    _Offers_PayOffer_Handler,
		},
		{
			MethodName: "ListOfferInvoices",
			Handler:    _Offers_ListOfferInvoices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "offersrpc/offers.proto",
}
