// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package bridgerpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BridgeClient is the client API for Bridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BridgeClient interface {
	// lncli: `bridge quote`
	// Quote asks what a swap would cost and creates the hold invoice to pay for
	// it. Which direction the swap runs is worked out by asking both nodes to
	// decode the invoice, not by reading its prefix here.
	//
	// A quote reserves nothing until the returned hold invoice is paid, but it
	// does fix a rate until expires_at.
	Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error)
	// lncli: `bridge swap`
	// LookupSwap reports what the bridge believes about a swap it has quoted,
	// including the preimage once there is one, which is the payer's proof that
	// the destination was paid.
	LookupSwap(ctx context.Context, in *LookupSwapRequest, opts ...grpc.CallOption) (*Swap, error)
	// lncli: `bridge status`
	// Status reports whether this node is in a position to serve swaps: which
	// directions are enabled, whether both chains can be measured, whether a
	// usable price is available, and how many swaps are in flight.
	//
	// It answers while the bridge is refusing everything, which is the case it
	// exists for.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type bridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewBridgeClient(cc grpc.ClientConnInterface) BridgeClient {
	return &bridgeClient{cc}
}

func (c *bridgeClient) Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error) {
	out := new(QuoteResponse)
	err := c.cc.Invoke(ctx, "/bridgerpc.Bridge/Quote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) LookupSwap(ctx context.Context, in *LookupSwapRequest, opts ...grpc.CallOption) (*Swap, error) {
	out := new(Swap)
	err := c.cc.Invoke(ctx, "/bridgerpc.Bridge/LookupSwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/bridgerpc.Bridge/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BridgeServer is the server API for Bridge service.
// All implementations must embed UnimplementedBridgeServer
// for forward compatibility
type BridgeServer interface {
	// lncli: `bridge quote`
	// Quote asks what a swap would cost and creates the hold invoice to pay for
	// it. Which direction the swap runs is worked out by asking both nodes to
	// decode the invoice, not by reading its prefix here.
	//
	// A quote reserves nothing until the returned hold invoice is paid, but it
	// does fix a rate until expires_at.
	Quote(context.Context, *QuoteRequest) (*QuoteResponse, error)
	// lncli: `bridge swap`
	// LookupSwap reports what the bridge believes about a swap it has quoted,
	// including the preimage once there is one, which is the payer's proof that
	// the destination was paid.
	LookupSwap(context.Context, *LookupSwapRequest) (*Swap, error)
	// lncli: `bridge status`
	// Status reports whether this node is in a position to serve swaps: which
	// directions are enabled, whether both chains can be measured, whether a
	// usable price is available, and how many swaps are in flight.
	//
	// It answers while the bridge is refusing everything, which is the case it
	// exists for.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedBridgeServer()
}

// UnimplementedBridgeServer must be embedded to have forward compatible implementations.
type UnimplementedBridgeServer struct {
}

func (UnimplementedBridgeServer) Quote(context.Context, *QuoteRequest) (*QuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Quote not implemented")
}
func (UnimplementedBridgeServer) LookupSwap(context.Context, *LookupSwapRequest) (*Swap, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupSwap not implemented")
}
func (UnimplementedBridgeServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedBridgeServer) mustEmbedUnimplementedBridgeServer() {}

// UnsafeBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BridgeServer will
// result in compilation errors.
type UnsafeBridgeServer interface {
	mustEmbedUnimplementedBridgeServer()
}

func RegisterBridgeServer(s grpc.ServiceRegistrar, srv BridgeServer) {
	s.RegisterService(&Bridge_ServiceDesc, srv)
}

func _Bridge_Quote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).Quote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bridgerpc.Bridge/Quote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).Quote(ctx, req.(*QuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_LookupSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).LookupSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bridgerpc.Bridge/LookupSwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).LookupSwap(ctx, req.(*LookupSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bridgerpc.Bridge/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Bridge_ServiceDesc is the grpc.ServiceDesc for Bridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridgerpc.Bridge",
	HandlerType: (*BridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Quote",
			Handler:    _Bridge_Quote_Handler,
		},
		{
			MethodName: "LookupSwap",
			Handler:    _Bridge_LookupSwap_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Bridge_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bridgerpc/bridge.proto",
}
