// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: bridgerpc/bridge.proto

package bridgerpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payment request the payer wants delivered, on whichever chain it is
	// for. It is never rewritten: its payment hash is what the hold invoice is
	// built on, and settling requires that exact preimage.
	Invoice       string `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *QuoteRequest) GetInvoice() string {
	if x != nil {
		return x.Invoice
	}
	return ""
}

type QuoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What the payer pays, on the other chain. It is a hold invoice and does not
	// settle until the bridge has delivered, which is the whole mechanism.
	HoldInvoice string `protobuf:"bytes,1,opt,name=hold_invoice,json=holdInvoice,proto3" json:"hold_invoice,omitempty"`
	// The payment hash both legs share, and the key to ask about this swap.
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// What the payer owes. Note that incoming and outgoing are in different
	// units: a millisatoshi on one chain is not a millisatoshi on the other.
	IncomingMsat uint64 `protobuf:"varint,3,opt,name=incoming_msat,json=incomingMsat,proto3" json:"incoming_msat,omitempty"`
	// What the destination receives.
	OutgoingMsat uint64 `protobuf:"varint,4,opt,name=outgoing_msat,json=outgoingMsat,proto3" json:"outgoing_msat,omitempty"`
	// Outgoing units per incoming unit.
	Rate float64 `protobuf:"fixed64,5,opt,name=rate,proto3" json:"rate,omitempty"`
	// The fraction charged on top of the rate.
	Spread float64 `protobuf:"fixed64,6,opt,name=spread,proto3" json:"spread,omitempty"`
	// The incoming leg's required CLTV, in blocks of the incoming chain. It is
	// sized in wall-clock by the margin policy and converted, so it is usually
	// far larger than a same-chain invoice would ask for.
	CltvDelta uint32 `protobuf:"varint,7,opt,name=cltv_delta,json=cltvDelta,proto3" json:"cltv_delta,omitempty"`
	// Which way this swap runs, for a payer deciding which node to pay from.
	Direction string `protobuf:"bytes,8,opt,name=direction,proto3" json:"direction,omitempty"`
	// The deadline for paying hold_invoice, as a Unix timestamp in seconds. Pay
	// it before this and the swap proceeds at the quoted rate; leave it and the
	// bridge cancels the hold invoice, after which paying it fails.
	//
	// It applies only while the invoice is unpaid. Once the incoming HTLC is
	// locked in the swap is no longer racing a clock in minutes, and cltv_delta
	// is what bounds it.
	ExpiresAt     int64 `protobuf:"varint,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse) ProtoMessage() {}

func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteResponse.ProtoReflect.Descriptor instead.
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *QuoteResponse) GetHoldInvoice() string {
	if x != nil {
		return x.HoldInvoice
	}
	return ""
}

func (x *QuoteResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *QuoteResponse) GetIncomingMsat() uint64 {
	if x != nil {
		return x.IncomingMsat
	}
	return 0
}

func (x *QuoteResponse) GetOutgoingMsat() uint64 {
	if x != nil {
		return x.OutgoingMsat
	}
	return 0
}

func (x *QuoteResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *QuoteResponse) GetSpread() float64 {
	if x != nil {
		return x.Spread
	}
	return 0
}

func (x *QuoteResponse) GetCltvDelta() uint32 {
	if x != nil {
		return x.CltvDelta
	}
	return 0
}

func (x *QuoteResponse) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *QuoteResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type LookupSwapRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payment hash the quote returned.
	Hash          []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupSwapRequest) Reset() {
	*x = LookupSwapRequest{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupSwapRequest) ProtoMessage() {}

func (x *LookupSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupSwapRequest.ProtoReflect.Descriptor instead.
func (*LookupSwapRequest) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *LookupSwapRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Swap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Hash  []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// What the bridge believes this swap is doing.
	State        string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	IncomingMsat uint64 `protobuf:"varint,3,opt,name=incoming_msat,json=incomingMsat,proto3" json:"incoming_msat,omitempty"`
	OutgoingMsat uint64 `protobuf:"varint,4,opt,name=outgoing_msat,json=outgoingMsat,proto3" json:"outgoing_msat,omitempty"`
	// Present once there is one. It is the payer's proof that the destination was
	// paid, and the value that claims the incoming hold invoice.
	Preimage      []byte `protobuf:"bytes,5,opt,name=preimage,proto3" json:"preimage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Swap) Reset() {
	*x = Swap{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Swap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Swap) ProtoMessage() {}

func (x *Swap) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Swap.ProtoReflect.Descriptor instead.
func (*Swap) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *Swap) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Swap) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Swap) GetIncomingMsat() uint64 {
	if x != nil {
		return x.IncomingMsat
	}
	return 0
}

func (x *Swap) GetOutgoingMsat() uint64 {
	if x != nil {
		return x.OutgoingMsat
	}
	return 0
}

func (x *Swap) GetPreimage() []byte {
	if x != nil {
		return x.Preimage
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{4}
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the operator has turned the bridge on.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The directions this node will currently quote. A direction disappears from
	// here when it is disabled or when the node on that side cannot be reached.
	Directions []string `protobuf:"bytes,2,rep,name=directions,proto3" json:"directions,omitempty"`
	// Why the bridge is refusing to quote, if it is. Empty when it is serving.
	// This is the field to read first: a bridge with no liquidity, an unsynced
	// node or a stale price refuses every swap, and the reason belongs here
	// rather than in a log.
	Refusals []string `protobuf:"bytes,3,rep,name=refusals,proto3" json:"refusals,omitempty"`
	// How many swaps are being driven right now.
	SwapsInFlight uint32 `protobuf:"varint,4,opt,name=swaps_in_flight,json=swapsInFlight,proto3" json:"swaps_in_flight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *StatusResponse) GetDirections() []string {
	if x != nil {
		return x.Directions
	}
	return nil
}

func (x *StatusResponse) GetRefusals() []string {
	if x != nil {
		return x.Refusals
	}
	return nil
}

func (x *StatusResponse) GetSwapsInFlight() uint32 {
	if x != nil {
		return x.SwapsInFlight
	}
	return 0
}

var File_bridgerpc_bridge_proto protoreflect.FileDescriptor

const file_bridgerpc_bridge_proto_rawDesc = "" +
	"\n" +
	"\x16bridgerpc/bridge.proto\x12\tbridgerpc\"(\n" +
	"\fQuoteRequest\x12\x18\n" +
	"\ainvoice\x18\x01 \x01(\tR\ainvoice\"\x98\x02\n" +
	"\rQuoteResponse\x12!\n" +
	"\fhold_invoice\x18\x01 \x01(\tR\vholdInvoice\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12#\n" +
	"\rincoming_msat\x18\x03 \x01(\x04R\fincomingMsat\x12#\n" +
	"\routgoing_msat\x18\x04 \x01(\x04R\foutgoingMsat\x12\x12\n" +
	"\x04rate\x18\x05 \x01(\x01R\x04rate\x12\x16\n" +
	"\x06spread\x18\x06 \x01(\x01R\x06spread\x12\x1d\n" +
	"\n" +
	"cltv_delta\x18\a \x01(\rR\tcltvDelta\x12\x1c\n" +
	"\tdirection\x18\b \x01(\tR\tdirection\x12\x1d\n" +
	"\n" +
	"expires_at\x18\t \x01(\x03R\texpiresAt\"'\n" +
	"\x11LookupSwapRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"\x96\x01\n" +
	"\x04Swap\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12#\n" +
	"\rincoming_msat\x18\x03 \x01(\x04R\fincomingMsat\x12#\n" +
	"\routgoing_msat\x18\x04 \x01(\x04R\foutgoingMsat\x12\x1a\n" +
	"\bpreimage\x18\x05 \x01(\fR\bpreimage\"\x0f\n" +
	"\rStatusRequest\"\x8e\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1e\n" +
	"\n" +
	"directions\x18\x02 \x03(\tR\n" +
	"directions\x12\x1a\n" +
	"\brefusals\x18\x03 \x03(\tR\brefusals\x12&\n" +
	"\x0fswaps_in_flight\x18\x04 \x01(\rR\rswapsInFlight2\xc0\x01\n" +
	"\x06Bridge\x12:\n" +
	"\x05Quote\x12\x17.bridgerpc.QuoteRequest\x1a\x18.bridgerpc.QuoteResponse\x12;\n" +
	"\n" +
	"LookupSwap\x12\x1c.bridgerpc.LookupSwapRequest\x1a\x0f.bridgerpc.Swap\x12=\n" +
	"\x06Status\x12\x18.bridgerpc.StatusRequest\x1a\x19.bridgerpc.StatusResponseB1Z/github.com/lightningnetwork/lnd/lnrpc/bridgerpcb\x06proto3"

var (
	file_bridgerpc_bridge_proto_rawDescOnce sync.Once
	file_bridgerpc_bridge_proto_rawDescData []byte
)

func file_bridgerpc_bridge_proto_rawDescGZIP() []byte {
	file_bridgerpc_bridge_proto_rawDescOnce.Do(func() {
		file_bridgerpc_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridgerpc_bridge_proto_rawDesc), len(file_bridgerpc_bridge_proto_rawDesc)))
	})
	return file_bridgerpc_bridge_proto_rawDescData
}

var file_bridgerpc_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bridgerpc_bridge_proto_goTypes = []any{
	(*QuoteRequest)(nil),      // 0: bridgerpc.QuoteRequest
	(*QuoteResponse)(nil),     // 1: bridgerpc.QuoteResponse
	(*LookupSwapRequest)(nil), // 2: bridgerpc.LookupSwapRequest
	(*Swap)(nil),              // 3: bridgerpc.Swap
	(*StatusRequest)(nil),     // 4: bridgerpc.StatusRequest
	(*StatusResponse)(nil),    // 5: bridgerpc.StatusResponse
}
var file_bridgerpc_bridge_proto_depIdxs = []int32{
	0, // 0: bridgerpc.Bridge.Quote:input_type -> bridgerpc.QuoteRequest
	2, // 1: bridgerpc.Bridge.LookupSwap:input_type -> bridgerpc.LookupSwapRequest
	4, // 2: bridgerpc.Bridge.Status:input_type -> bridgerpc.StatusRequest
	1, // 3: bridgerpc.Bridge.Quote:output_type -> bridgerpc.QuoteResponse
	3, // 4: bridgerpc.Bridge.LookupSwap:output_type -> bridgerpc.Swap
	5, // 5: bridgerpc.Bridge.Status:output_type -> bridgerpc.StatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bridgerpc_bridge_proto_init() }
func file_bridgerpc_bridge_proto_init() {
	if File_bridgerpc_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridgerpc_bridge_proto_rawDesc), len(file_bridgerpc_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridgerpc_bridge_proto_goTypes,
		DependencyIndexes: file_bridgerpc_bridge_proto_depIdxs,
		MessageInfos:      file_bridgerpc_bridge_proto_msgTypes,
	}.Build()
	File_bridgerpc_bridge_proto = out.File
	file_bridgerpc_bridge_proto_goTypes = nil
	file_bridgerpc_bridge_proto_depIdxs = nil
}
