// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: bridgerpc/bridge.proto

package bridgerpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payment request the payer wants delivered, on whichever chain it is
	// for. It is never rewritten: its payment hash is what the hold invoice is
	// built on, and settling requires that exact preimage.
	Invoice       string `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *QuoteRequest) GetInvoice() string {
	if x != nil {
		return x.Invoice
	}
	return ""
}

type QuoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What the payer pays, on the other chain. It is a hold invoice and does not
	// settle until the bridge has delivered, which is the whole mechanism.
	HoldInvoice string `protobuf:"bytes,1,opt,name=hold_invoice,json=holdInvoice,proto3" json:"hold_invoice,omitempty"`
	// The payment hash both legs share, and the key to ask about this swap.
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// What the payer owes. Note that incoming and outgoing are in different
	// units: a millisatoshi on one chain is not a millisatoshi on the other.
	IncomingMsat uint64 `protobuf:"varint,3,opt,name=incoming_msat,json=incomingMsat,proto3" json:"incoming_msat,omitempty"`
	// What the destination receives.
	OutgoingMsat uint64 `protobuf:"varint,4,opt,name=outgoing_msat,json=outgoingMsat,proto3" json:"outgoing_msat,omitempty"`
	// Outgoing units per incoming unit.
	Rate float64 `protobuf:"fixed64,5,opt,name=rate,proto3" json:"rate,omitempty"`
	// The fraction charged on top of the rate.
	Spread float64 `protobuf:"fixed64,6,opt,name=spread,proto3" json:"spread,omitempty"`
	// The incoming leg's required CLTV, in blocks of the incoming chain. It is
	// sized in wall-clock by the margin policy and converted, so it is usually
	// far larger than a same-chain invoice would ask for.
	CltvDelta uint32 `protobuf:"varint,7,opt,name=cltv_delta,json=cltvDelta,proto3" json:"cltv_delta,omitempty"`
	// Which way this swap runs, for a payer deciding which node to pay from.
	Direction string `protobuf:"bytes,8,opt,name=direction,proto3" json:"direction,omitempty"`
	// The deadline for paying hold_invoice, as a Unix timestamp in seconds. Pay
	// it before this and the swap proceeds at the quoted rate; leave it and the
	// bridge cancels the hold invoice, after which paying it fails.
	//
	// It applies only while the invoice is unpaid. Once the incoming HTLC is
	// locked in the swap is no longer racing a clock in minutes, and cltv_delta
	// is what bounds it.
	ExpiresAt     int64 `protobuf:"varint,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse) ProtoMessage() {}

func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteResponse.ProtoReflect.Descriptor instead.
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *QuoteResponse) GetHoldInvoice() string {
	if x != nil {
		return x.HoldInvoice
	}
	return ""
}

func (x *QuoteResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *QuoteResponse) GetIncomingMsat() uint64 {
	if x != nil {
		return x.IncomingMsat
	}
	return 0
}

func (x *QuoteResponse) GetOutgoingMsat() uint64 {
	if x != nil {
		return x.OutgoingMsat
	}
	return 0
}

func (x *QuoteResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *QuoteResponse) GetSpread() float64 {
	if x != nil {
		return x.Spread
	}
	return 0
}

func (x *QuoteResponse) GetCltvDelta() uint32 {
	if x != nil {
		return x.CltvDelta
	}
	return 0
}

func (x *QuoteResponse) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *QuoteResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type LookupSwapRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payment hash the quote returned.
	Hash          []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupSwapRequest) Reset() {
	*x = LookupSwapRequest{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupSwapRequest) ProtoMessage() {}

func (x *LookupSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupSwapRequest.ProtoReflect.Descriptor instead.
func (*LookupSwapRequest) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *LookupSwapRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Swap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Hash  []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// What the bridge believes this swap is doing.
	State        string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	IncomingMsat uint64 `protobuf:"varint,3,opt,name=incoming_msat,json=incomingMsat,proto3" json:"incoming_msat,omitempty"`
	OutgoingMsat uint64 `protobuf:"varint,4,opt,name=outgoing_msat,json=outgoingMsat,proto3" json:"outgoing_msat,omitempty"`
	// Present once there is one. It is the payer's proof that the destination was
	// paid, and the value that claims the incoming hold invoice.
	Preimage      []byte `protobuf:"bytes,5,opt,name=preimage,proto3" json:"preimage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Swap) Reset() {
	*x = Swap{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Swap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Swap) ProtoMessage() {}

func (x *Swap) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Swap.ProtoReflect.Descriptor instead.
func (*Swap) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *Swap) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Swap) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Swap) GetIncomingMsat() uint64 {
	if x != nil {
		return x.IncomingMsat
	}
	return 0
}

func (x *Swap) GetOutgoingMsat() uint64 {
	if x != nil {
		return x.OutgoingMsat
	}
	return 0
}

func (x *Swap) GetPreimage() []byte {
	if x != nil {
		return x.Preimage
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{4}
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the operator has turned the bridge on.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The directions this node will currently quote. A direction disappears from
	// here when it is disabled or when the node on that side cannot be reached.
	Directions []string `protobuf:"bytes,2,rep,name=directions,proto3" json:"directions,omitempty"`
	// Why the bridge is refusing to quote, if it is. Empty when it is serving.
	// This is the field to read first: a bridge with no liquidity, an unsynced
	// node or a stale price refuses every swap, and the reason belongs here
	// rather than in a log.
	Refusals []string `protobuf:"bytes,3,rep,name=refusals,proto3" json:"refusals,omitempty"`
	// How many swaps are being driven right now.
	SwapsInFlight uint32 `protobuf:"varint,4,opt,name=swaps_in_flight,json=swapsInFlight,proto3" json:"swaps_in_flight,omitempty"`
	// The rate in force, as SHA256 coin per BLAKE2b coin.
	Rate float64 `protobuf:"fixed64,5,opt,name=rate,proto3" json:"rate,omitempty"`
	// When it was set, as a Unix timestamp in seconds.
	RateSetAt int64 `protobuf:"varint,6,opt,name=rate_set_at,json=rateSetAt,proto3" json:"rate_set_at,omitempty"`
	// When it stops being used, as a Unix timestamp in seconds, or zero if the
	// bridge allows a rate of any age.
	RateExpiresAt int64 `protobuf:"varint,7,opt,name=rate_expires_at,json=rateExpiresAt,proto3" json:"rate_expires_at,omitempty"`
	// Swaps that need the operator: ones that ended lost (paid out and the
	// claim on the money coming in could not be settled) or that the bridge
	// stopped driving because it must not decide them alone. Each is the
	// payment hash, the state and why. The bridge keeps quoting; these are for
	// a person to look at.
	NeedsOperator []string `protobuf:"bytes,8,rep,name=needs_operator,json=needsOperator,proto3" json:"needs_operator,omitempty"`
	// The Lightning node on the SHA256 chain: how far it has got and what it
	// holds. Present whenever the bridge is enabled, including while it cannot
	// start, since that node is usually why.
	Sha256Node *Sha256Node `protobuf:"bytes,9,opt,name=sha256_node,json=sha256Node,proto3" json:"sha256_node,omitempty"`
	// How many swaps the journal holds unfinished: being driven, waiting to be,
	// or stopped for the operator. Answered whether the bridge is on, off and
	// finishing them, or not up (then as last read). A lost swap is final and
	// not counted; it stays in needs_operator. This is what to wait on before
	// turning the bridge off or changing its SHA256 node.
	Unfinished    uint32 `protobuf:"varint,10,opt,name=unfinished,proto3" json:"unfinished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *StatusResponse) GetDirections() []string {
	if x != nil {
		return x.Directions
	}
	return nil
}

func (x *StatusResponse) GetRefusals() []string {
	if x != nil {
		return x.Refusals
	}
	return nil
}

func (x *StatusResponse) GetSwapsInFlight() uint32 {
	if x != nil {
		return x.SwapsInFlight
	}
	return 0
}

func (x *StatusResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *StatusResponse) GetRateSetAt() int64 {
	if x != nil {
		return x.RateSetAt
	}
	return 0
}

func (x *StatusResponse) GetRateExpiresAt() int64 {
	if x != nil {
		return x.RateExpiresAt
	}
	return 0
}

func (x *StatusResponse) GetNeedsOperator() []string {
	if x != nil {
		return x.NeedsOperator
	}
	return nil
}

func (x *StatusResponse) GetSha256Node() *Sha256Node {
	if x != nil {
		return x.Sha256Node
	}
	return nil
}

func (x *StatusResponse) GetUnfinished() uint32 {
	if x != nil {
		return x.Unfinished
	}
	return 0
}

type Sha256Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// supervised when this node runs it for the bridge, external when it is a
	// node the operator already ran.
	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// Where that node is, as a stable code: starting, creating_wallet, locked,
	// syncing, ready, unreachable, not_ours or error.
	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// The same in a sentence, including what to do about it.
	Detail string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	// Its identity key, hex, and the addresses it can be reached at.
	IdentityPubkey string   `protobuf:"bytes,4,opt,name=identity_pubkey,json=identityPubkey,proto3" json:"identity_pubkey,omitempty"`
	Uris           []string `protobuf:"bytes,5,rep,name=uris,proto3" json:"uris,omitempty"`
	SyncedToChain  bool     `protobuf:"varint,6,opt,name=synced_to_chain,json=syncedToChain,proto3" json:"synced_to_chain,omitempty"`
	BlockHeight    uint32   `protobuf:"varint,7,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// Its on-chain wallet: what can be spent now, and what is still
	// confirming.
	OnchainConfirmedSat   int64  `protobuf:"varint,8,opt,name=onchain_confirmed_sat,json=onchainConfirmedSat,proto3" json:"onchain_confirmed_sat,omitempty"`
	OnchainUnconfirmedSat int64  `protobuf:"varint,9,opt,name=onchain_unconfirmed_sat,json=onchainUnconfirmedSat,proto3" json:"onchain_unconfirmed_sat,omitempty"`
	ActiveChannels        uint32 `protobuf:"varint,10,opt,name=active_channels,json=activeChannels,proto3" json:"active_channels,omitempty"`
	InactiveChannels      uint32 `protobuf:"varint,11,opt,name=inactive_channels,json=inactiveChannels,proto3" json:"inactive_channels,omitempty"`
	PendingChannels       uint32 `protobuf:"varint,12,opt,name=pending_channels,json=pendingChannels,proto3" json:"pending_channels,omitempty"`
	// What its channels could send and receive now, in millisatoshis. Sending
	// is what the bridge pays out with on the SHA256 chain.
	OutboundMsat uint64 `protobuf:"varint,13,opt,name=outbound_msat,json=outboundMsat,proto3" json:"outbound_msat,omitempty"`
	InboundMsat  uint64 `protobuf:"varint,14,opt,name=inbound_msat,json=inboundMsat,proto3" json:"inbound_msat,omitempty"`
	Peers        uint32 `protobuf:"varint,15,opt,name=peers,proto3" json:"peers,omitempty"`
	// The lnd version it runs.
	Version       string `protobuf:"bytes,16,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sha256Node) Reset() {
	*x = Sha256Node{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sha256Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sha256Node) ProtoMessage() {}

func (x *Sha256Node) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sha256Node.ProtoReflect.Descriptor instead.
func (*Sha256Node) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *Sha256Node) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Sha256Node) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Sha256Node) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Sha256Node) GetIdentityPubkey() string {
	if x != nil {
		return x.IdentityPubkey
	}
	return ""
}

func (x *Sha256Node) GetUris() []string {
	if x != nil {
		return x.Uris
	}
	return nil
}

func (x *Sha256Node) GetSyncedToChain() bool {
	if x != nil {
		return x.SyncedToChain
	}
	return false
}

func (x *Sha256Node) GetBlockHeight() uint32 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *Sha256Node) GetOnchainConfirmedSat() int64 {
	if x != nil {
		return x.OnchainConfirmedSat
	}
	return 0
}

func (x *Sha256Node) GetOnchainUnconfirmedSat() int64 {
	if x != nil {
		return x.OnchainUnconfirmedSat
	}
	return 0
}

func (x *Sha256Node) GetActiveChannels() uint32 {
	if x != nil {
		return x.ActiveChannels
	}
	return 0
}

func (x *Sha256Node) GetInactiveChannels() uint32 {
	if x != nil {
		return x.InactiveChannels
	}
	return 0
}

func (x *Sha256Node) GetPendingChannels() uint32 {
	if x != nil {
		return x.PendingChannels
	}
	return 0
}

func (x *Sha256Node) GetOutboundMsat() uint64 {
	if x != nil {
		return x.OutboundMsat
	}
	return 0
}

func (x *Sha256Node) GetInboundMsat() uint64 {
	if x != nil {
		return x.InboundMsat
	}
	return 0
}

func (x *Sha256Node) GetPeers() uint32 {
	if x != nil {
		return x.Peers
	}
	return 0
}

func (x *Sha256Node) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ExportSha256SeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportSha256SeedRequest) Reset() {
	*x = ExportSha256SeedRequest{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSha256SeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSha256SeedRequest) ProtoMessage() {}

func (x *ExportSha256SeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSha256SeedRequest.ProtoReflect.Descriptor instead.
func (*ExportSha256SeedRequest) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{7}
}

type ExportSha256SeedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The 24-word aezeed phrase, with no passphrase. Each call salts it afresh,
	// so the words differ from call to call; every one restores the same node.
	Mnemonic []string `protobuf:"bytes,1,rep,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	// The same seed as a BIP32 root key (xprv on mainnet), which
	// `lncli create` also accepts.
	ExtendedMasterKey string `protobuf:"bytes,2,opt,name=extended_master_key,json=extendedMasterKey,proto3" json:"extended_master_key,omitempty"`
	// The wallet birthday, as a Unix timestamp: where a restore rescans from.
	Birthday int64 `protobuf:"varint,3,opt,name=birthday,proto3" json:"birthday,omitempty"`
	// The identity key a node restored from either will have, hex.
	IdentityPubkey string `protobuf:"bytes,4,opt,name=identity_pubkey,json=identityPubkey,proto3" json:"identity_pubkey,omitempty"`
	// How the seed is derived, so it can be checked without this code.
	Derivation    string `protobuf:"bytes,5,opt,name=derivation,proto3" json:"derivation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportSha256SeedResponse) Reset() {
	*x = ExportSha256SeedResponse{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSha256SeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSha256SeedResponse) ProtoMessage() {}

func (x *ExportSha256SeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSha256SeedResponse.ProtoReflect.Descriptor instead.
func (*ExportSha256SeedResponse) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *ExportSha256SeedResponse) GetMnemonic() []string {
	if x != nil {
		return x.Mnemonic
	}
	return nil
}

func (x *ExportSha256SeedResponse) GetExtendedMasterKey() string {
	if x != nil {
		return x.ExtendedMasterKey
	}
	return ""
}

func (x *ExportSha256SeedResponse) GetBirthday() int64 {
	if x != nil {
		return x.Birthday
	}
	return 0
}

func (x *ExportSha256SeedResponse) GetIdentityPubkey() string {
	if x != nil {
		return x.IdentityPubkey
	}
	return ""
}

func (x *ExportSha256SeedResponse) GetDerivation() string {
	if x != nil {
		return x.Derivation
	}
	return ""
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{9}
}

type DirectionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// toSHA256 or toBLAKE2b.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Whether a quote in this direction could succeed right now.
	Open bool `protobuf:"varint,2,opt,name=open,proto3" json:"open,omitempty"`
	// Why not, when it could not: a stable code and a sentence.
	RefusalCode string `protobuf:"bytes,3,opt,name=refusal_code,json=refusalCode,proto3" json:"refusal_code,omitempty"`
	Refusal     string `protobuf:"bytes,4,opt,name=refusal,proto3" json:"refusal,omitempty"`
	// Outgoing units per incoming unit. For toSHA256, SHA256 coin per BLAKE2b
	// coin.
	Rate float64 `protobuf:"fixed64,5,opt,name=rate,proto3" json:"rate,omitempty"`
	// When the rate was set, as a Unix timestamp in seconds.
	RateSetAt int64 `protobuf:"varint,6,opt,name=rate_set_at,json=rateSetAt,proto3" json:"rate_set_at,omitempty"`
	// The fraction charged on top of the rate at the bridge's current position.
	// It can move between this call and a quote.
	Spread float64 `protobuf:"fixed64,7,opt,name=spread,proto3" json:"spread,omitempty"`
	// Bounds on the invoice to be paid, in the outgoing chain's millisatoshis.
	MinMsat       uint64 `protobuf:"varint,8,opt,name=min_msat,json=minMsat,proto3" json:"min_msat,omitempty"`
	MaxMsat       uint64 `protobuf:"varint,9,opt,name=max_msat,json=maxMsat,proto3" json:"max_msat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectionInfo) Reset() {
	*x = DirectionInfo{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectionInfo) ProtoMessage() {}

func (x *DirectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectionInfo.ProtoReflect.Descriptor instead.
func (*DirectionInfo) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *DirectionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirectionInfo) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *DirectionInfo) GetRefusalCode() string {
	if x != nil {
		return x.RefusalCode
	}
	return ""
}

func (x *DirectionInfo) GetRefusal() string {
	if x != nil {
		return x.Refusal
	}
	return ""
}

func (x *DirectionInfo) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *DirectionInfo) GetRateSetAt() int64 {
	if x != nil {
		return x.RateSetAt
	}
	return 0
}

func (x *DirectionInfo) GetSpread() float64 {
	if x != nil {
		return x.Spread
	}
	return 0
}

func (x *DirectionInfo) GetMinMsat() uint64 {
	if x != nil {
		return x.MinMsat
	}
	return 0
}

func (x *DirectionInfo) GetMaxMsat() uint64 {
	if x != nil {
		return x.MaxMsat
	}
	return 0
}

type InfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The version of the payer API this bridge speaks.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// This node's key. Every hold invoice the bridge issues on this chain is
	// payable to exactly this key.
	Node string `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	// One entry per enabled direction.
	Directions    []*DirectionInfo `protobuf:"bytes,3,rep,name=directions,proto3" json:"directions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *InfoResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *InfoResponse) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *InfoResponse) GetDirections() []*DirectionInfo {
	if x != nil {
		return x.Directions
	}
	return nil
}

type SetRateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new rate, as SHA256 coin per BLAKE2b coin.
	Rate          float64 `protobuf:"fixed64,1,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRateRequest) Reset() {
	*x = SetRateRequest{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRateRequest) ProtoMessage() {}

func (x *SetRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRateRequest.ProtoReflect.Descriptor instead.
func (*SetRateRequest) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{12}
}

func (x *SetRateRequest) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type SetRateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The rate now in force and when it was set, as a Unix timestamp.
	Rate          float64 `protobuf:"fixed64,1,opt,name=rate,proto3" json:"rate,omitempty"`
	RateSetAt     int64   `protobuf:"varint,2,opt,name=rate_set_at,json=rateSetAt,proto3" json:"rate_set_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRateResponse) Reset() {
	*x = SetRateResponse{}
	mi := &file_bridgerpc_bridge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRateResponse) ProtoMessage() {}

func (x *SetRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridgerpc_bridge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRateResponse.ProtoReflect.Descriptor instead.
func (*SetRateResponse) Descriptor() ([]byte, []int) {
	return file_bridgerpc_bridge_proto_rawDescGZIP(), []int{13}
}

func (x *SetRateResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *SetRateResponse) GetRateSetAt() int64 {
	if x != nil {
		return x.RateSetAt
	}
	return 0
}

var File_bridgerpc_bridge_proto protoreflect.FileDescriptor

const file_bridgerpc_bridge_proto_rawDesc = "" +
	"\n" +
	"\x16bridgerpc/bridge.proto\x12\tbridgerpc\"(\n" +
	"\fQuoteRequest\x12\x18\n" +
	"\ainvoice\x18\x01 \x01(\tR\ainvoice\"\x98\x02\n" +
	"\rQuoteResponse\x12!\n" +
	"\fhold_invoice\x18\x01 \x01(\tR\vholdInvoice\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12#\n" +
	"\rincoming_msat\x18\x03 \x01(\x04R\fincomingMsat\x12#\n" +
	"\routgoing_msat\x18\x04 \x01(\x04R\foutgoingMsat\x12\x12\n" +
	"\x04rate\x18\x05 \x01(\x01R\x04rate\x12\x16\n" +
	"\x06spread\x18\x06 \x01(\x01R\x06spread\x12\x1d\n" +
	"\n" +
	"cltv_delta\x18\a \x01(\rR\tcltvDelta\x12\x1c\n" +
	"\tdirection\x18\b \x01(\tR\tdirection\x12\x1d\n" +
	"\n" +
	"expires_at\x18\t \x01(\x03R\texpiresAt\"'\n" +
	"\x11LookupSwapRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"\x96\x01\n" +
	"\x04Swap\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12#\n" +
	"\rincoming_msat\x18\x03 \x01(\x04R\fincomingMsat\x12#\n" +
	"\routgoing_msat\x18\x04 \x01(\x04R\foutgoingMsat\x12\x1a\n" +
	"\bpreimage\x18\x05 \x01(\fR\bpreimage\"\x0f\n" +
	"\rStatusRequest\"\xe9\x02\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1e\n" +
	"\n" +
	"directions\x18\x02 \x03(\tR\n" +
	"directions\x12\x1a\n" +
	"\brefusals\x18\x03 \x03(\tR\brefusals\x12&\n" +
	"\x0fswaps_in_flight\x18\x04 \x01(\rR\rswapsInFlight\x12\x12\n" +
	"\x04rate\x18\x05 \x01(\x01R\x04rate\x12\x1e\n" +
	"\vrate_set_at\x18\x06 \x01(\x03R\trateSetAt\x12&\n" +
	"\x0frate_expires_at\x18\a \x01(\x03R\rrateExpiresAt\x12%\n" +
	"\x0eneeds_operator\x18\b \x03(\tR\rneedsOperator\x126\n" +
	"\vsha256_node\x18\t \x01(\v2\x15.bridgerpc.Sha256NodeR\n" +
	"sha256Node\x12\x1e\n" +
	"\n" +
	"unfinished\x18\n" +
	" \x01(\rR\n" +
	"unfinished\"\xbb\x04\n" +
	"\n" +
	"Sha256Node\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12'\n" +
	"\x0fidentity_pubkey\x18\x04 \x01(\tR\x0eidentityPubkey\x12\x12\n" +
	"\x04uris\x18\x05 \x03(\tR\x04uris\x12&\n" +
	"\x0fsynced_to_chain\x18\x06 \x01(\bR\rsyncedToChain\x12!\n" +
	"\fblock_height\x18\a \x01(\rR\vblockHeight\x122\n" +
	"\x15onchain_confirmed_sat\x18\b \x01(\x03R\x13onchainConfirmedSat\x126\n" +
	"\x17onchain_unconfirmed_sat\x18\t \x01(\x03R\x15onchainUnconfirmedSat\x12'\n" +
	"\x0factive_channels\x18\n" +
	" \x01(\rR\x0eactiveChannels\x12+\n" +
	"\x11inactive_channels\x18\v \x01(\rR\x10inactiveChannels\x12)\n" +
	"\x10pending_channels\x18\f \x01(\rR\x0fpendingChannels\x12#\n" +
	"\routbound_msat\x18\r \x01(\x04R\foutboundMsat\x12!\n" +
	"\finbound_msat\x18\x0e \x01(\x04R\vinboundMsat\x12\x14\n" +
	"\x05peers\x18\x0f \x01(\rR\x05peers\x12\x18\n" +
	"\aversion\x18\x10 \x01(\tR\aversion\"\x19\n" +
	"\x17ExportSha256SeedRequest\"\xcb\x01\n" +
	"\x18ExportSha256SeedResponse\x12\x1a\n" +
	"\bmnemonic\x18\x01 \x03(\tR\bmnemonic\x12.\n" +
	"\x13extended_master_key\x18\x02 \x01(\tR\x11extendedMasterKey\x12\x1a\n" +
	"\bbirthday\x18\x03 \x01(\x03R\bbirthday\x12'\n" +
	"\x0fidentity_pubkey\x18\x04 \x01(\tR\x0eidentityPubkey\x12\x1e\n" +
	"\n" +
	"derivation\x18\x05 \x01(\tR\n" +
	"derivation\"\r\n" +
	"\vInfoRequest\"\xf6\x01\n" +
	"\rDirectionInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04open\x18\x02 \x01(\bR\x04open\x12!\n" +
	"\frefusal_code\x18\x03 \x01(\tR\vrefusalCode\x12\x18\n" +
	"\arefusal\x18\x04 \x01(\tR\arefusal\x12\x12\n" +
	"\x04rate\x18\x05 \x01(\x01R\x04rate\x12\x1e\n" +
	"\vrate_set_at\x18\x06 \x01(\x03R\trateSetAt\x12\x16\n" +
	"\x06spread\x18\a \x01(\x01R\x06spread\x12\x19\n" +
	"\bmin_msat\x18\b \x01(\x04R\aminMsat\x12\x19\n" +
	"\bmax_msat\x18\t \x01(\x04R\amaxMsat\"v\n" +
	"\fInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x128\n" +
	"\n" +
	"directions\x18\x03 \x03(\v2\x18.bridgerpc.DirectionInfoR\n" +
	"directions\"$\n" +
	"\x0eSetRateRequest\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\x01R\x04rate\"E\n" +
	"\x0fSetRateResponse\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\x01R\x04rate\x12\x1e\n" +
	"\vrate_set_at\x18\x02 \x01(\x03R\trateSetAt2\x98\x03\n" +
	"\x06Bridge\x12:\n" +
	"\x05Quote\x12\x17.bridgerpc.QuoteRequest\x1a\x18.bridgerpc.QuoteResponse\x12;\n" +
	"\n" +
	"LookupSwap\x12\x1c.bridgerpc.LookupSwapRequest\x1a\x0f.bridgerpc.Swap\x12=\n" +
	"\x06Status\x12\x18.bridgerpc.StatusRequest\x1a\x19.bridgerpc.StatusResponse\x127\n" +
	"\x04Info\x12\x16.bridgerpc.InfoRequest\x1a\x17.bridgerpc.InfoResponse\x12@\n" +
	"\aSetRate\x12\x19.bridgerpc.SetRateRequest\x1a\x1a.bridgerpc.SetRateResponse\x12[\n" +
	"\x10ExportSha256Seed\x12\".bridgerpc.ExportSha256SeedRequest\x1a#.bridgerpc.ExportSha256SeedResponseB1Z/github.com/lightningnetwork/lnd/lnrpc/bridgerpcb\x06proto3"

var (
	file_bridgerpc_bridge_proto_rawDescOnce sync.Once
	file_bridgerpc_bridge_proto_rawDescData []byte
)

func file_bridgerpc_bridge_proto_rawDescGZIP() []byte {
	file_bridgerpc_bridge_proto_rawDescOnce.Do(func() {
		file_bridgerpc_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridgerpc_bridge_proto_rawDesc), len(file_bridgerpc_bridge_proto_rawDesc)))
	})
	return file_bridgerpc_bridge_proto_rawDescData
}

var file_bridgerpc_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_bridgerpc_bridge_proto_goTypes = []any{
	(*QuoteRequest)(nil),             // 0: bridgerpc.QuoteRequest
	(*QuoteResponse)(nil),            // 1: bridgerpc.QuoteResponse
	(*LookupSwapRequest)(nil),        // 2: bridgerpc.LookupSwapRequest
	(*Swap)(nil),                     // 3: bridgerpc.Swap
	(*StatusRequest)(nil),            // 4: bridgerpc.StatusRequest
	(*StatusResponse)(nil),           // 5: bridgerpc.StatusResponse
	(*Sha256Node)(nil),               // 6: bridgerpc.Sha256Node
	(*ExportSha256SeedRequest)(nil),  // 7: bridgerpc.ExportSha256SeedRequest
	(*ExportSha256SeedResponse)(nil), // 8: bridgerpc.ExportSha256SeedResponse
	(*InfoRequest)(nil),              // 9: bridgerpc.InfoRequest
	(*DirectionInfo)(nil),            // 10: bridgerpc.DirectionInfo
	(*InfoResponse)(nil),             // 11: bridgerpc.InfoResponse
	(*SetRateRequest)(nil),           // 12: bridgerpc.SetRateRequest
	(*SetRateResponse)(nil),          // 13: bridgerpc.SetRateResponse
}
var file_bridgerpc_bridge_proto_depIdxs = []int32{
	6,  // 0: bridgerpc.StatusResponse.sha256_node:type_name -> bridgerpc.Sha256Node
	10, // 1: bridgerpc.InfoResponse.directions:type_name -> bridgerpc.DirectionInfo
	0,  // 2: bridgerpc.Bridge.Quote:input_type -> bridgerpc.QuoteRequest
	2,  // 3: bridgerpc.Bridge.LookupSwap:input_type -> bridgerpc.LookupSwapRequest
	4,  // 4: bridgerpc.Bridge.Status:input_type -> bridgerpc.StatusRequest
	9,  // 5: bridgerpc.Bridge.Info:input_type -> bridgerpc.InfoRequest
	12, // 6: bridgerpc.Bridge.SetRate:input_type -> bridgerpc.SetRateRequest
	7,  // 7: bridgerpc.Bridge.ExportSha256Seed:input_type -> bridgerpc.ExportSha256SeedRequest
	1,  // 8: bridgerpc.Bridge.Quote:output_type -> bridgerpc.QuoteResponse
	3,  // 9: bridgerpc.Bridge.LookupSwap:output_type -> bridgerpc.Swap
	5,  // 10: bridgerpc.Bridge.Status:output_type -> bridgerpc.StatusResponse
	11, // 11: bridgerpc.Bridge.Info:output_type -> bridgerpc.InfoResponse
	13, // 12: bridgerpc.Bridge.SetRate:output_type -> bridgerpc.SetRateResponse
	8,  // 13: bridgerpc.Bridge.ExportSha256Seed:output_type -> bridgerpc.ExportSha256SeedResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_bridgerpc_bridge_proto_init() }
func file_bridgerpc_bridge_proto_init() {
	if File_bridgerpc_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridgerpc_bridge_proto_rawDesc), len(file_bridgerpc_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridgerpc_bridge_proto_goTypes,
		DependencyIndexes: file_bridgerpc_bridge_proto_depIdxs,
		MessageInfos:      file_bridgerpc_bridge_proto_msgTypes,
	}.Build()
	File_bridgerpc_bridge_proto = out.File
	file_bridgerpc_bridge_proto_goTypes = nil
	file_bridgerpc_bridge_proto_depIdxs = nil
}
